"""API request/response schemas.

This file is the stable contract between the ai-model service and the
Spring Boot backend. Field names here should not change without notifying
the backend team.
"""

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Gender(str, Enum):
    MALE = "Male"
    FEMALE = "Female"
    OTHER = "Other"


class RiskLevel(str, Enum):
    LOW = "Low"
    MODERATE = "Moderate"
    HIGH = "High"


class PatientHealthProfile(BaseModel):
    """Patient-supplied health information.

    Only age and gender are required; every clinical value is optional and
    will be imputed by the trained preprocessing pipelines when absent
    (reported back via ``features_imputed``).
    """

    age: int = Field(..., ge=1, le=120, description="Age in years")
    gender: Gender

    height_cm: Optional[float] = Field(None, gt=30, le=260)
    weight_kg: Optional[float] = Field(None, gt=0, le=400)
    bmi: Optional[float] = Field(None, ge=10, le=80)

    systolic_bp: Optional[float] = Field(None, ge=50, le=300, description="mmHg")
    diastolic_bp: Optional[float] = Field(None, ge=30, le=200, description="mmHg")

    fasting_glucose: Optional[float] = Field(None, ge=20, le=700, description="mg/dL")
    hba1c: Optional[float] = Field(None, ge=3, le=20, description="percent")
    cholesterol: Optional[float] = Field(None, ge=80, le=700, description="mg/dL")

    serum_creatinine: Optional[float] = Field(None, ge=0, le=25, description="mg/dL")
    blood_urea: Optional[float] = Field(None, ge=0, le=400, description="mg/dL")
    hemoglobin: Optional[float] = Field(None, ge=2, le=25, description="g/dL")

    # Urinalysis values (optional; consumed by the kidney model)
    urine_specific_gravity: Optional[float] = Field(None, ge=1.0, le=1.06)
    urine_albumin: Optional[int] = Field(None, ge=0, le=5)
    urine_sugar: Optional[int] = Field(None, ge=0, le=5)

    # Cardiac diagnostics (optional; consumed by the heart model)
    chest_pain_type: Optional[int] = Field(None, ge=1, le=4)
    max_heart_rate: Optional[float] = Field(None, ge=50, le=250)
    exercise_angina: Optional[bool] = None
    st_depression: Optional[float] = Field(None, ge=0, le=10)

    pregnancies: Optional[int] = Field(None, ge=0, le=20)

    smoker: bool = False
    hypertension: bool = False
    has_diabetes: Optional[bool] = None
    family_history_diabetes: bool = False
    family_history_heart_disease: bool = False

    symptoms: list[str] = Field(default_factory=list)


class DiseaseRisk(BaseModel):
    probability: float = Field(..., ge=0, le=1)
    level: RiskLevel
    top_factors: list[str] = Field(default_factory=list)


class OverallRisk(BaseModel):
    score: float = Field(..., ge=0, le=1)
    level: RiskLevel


class DiabetesRisk(DiseaseRisk):
    pass


class HeartRisk(DiseaseRisk):
    pass


class KidneyRisk(DiseaseRisk):
    pass


class DiseaseRisks(BaseModel):
    diabetes: DiabetesRisk
    heart: HeartRisk
    kidney: KidneyRisk


class AssessmentRequest(BaseModel):
    patient: PatientHealthProfile


class AssessmentResponse(BaseModel):
    overall_risk: OverallRisk
    disease_risks: DiseaseRisks
    risk_areas: list[str] = Field(default_factory=list)
    recommended_tests: list[str] = Field(default_factory=list)
    recommended_specialists: list[str] = Field(default_factory=list)
    features_imputed: list[str] = Field(default_factory=list)
    disclaimer: str


DISCLAIMER = (
    "This is a screening-level risk assessment generated by an AI model, "
    "not a medical diagnosis. Consult a qualified healthcare professional "
    "for any medical concern."
)
